[package]
name = "rdma"
version = "0.1.0-dev"
edition = "2021"

[dependencies]
asc = "0.1.0"
const-str = "0.3.1"
hex-simd = "0.5.0"
libc = "0.2.126"
numeric_cast = "0.1.2"
rdma-sys = { path = "../rdma-sys" }
scopeguard = "1.1.0"
