[package]
name = "rdma-pingpong"
version = "0.4.0-dev"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.58"
bincode = "1.3.3"
clap = { version = "3.2.8", features = ["derive"] }
numeric_cast = "0.1.2"
rdma = { path = "../../crates/rdma", features = ["serde"] }
serde = { version = "1.0.138", features = ["derive"] }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.14", features = ["env-filter"] }
