[package]
name = "rdma-tool"
version = "0.1.0-dev"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.57", features = ["backtrace"] }
clap = { version = "3.1.18", features = ["derive"] }
rdma = { path = "../rdma" }
tabled = "0.7.0"
